### PR TITLE
Output Checksum to Stats File

### PR DESCRIPTION
**Pull request by arunthirupathi**
1) Output Checksum to stats file, can be used for individual file
validation
2) Open the stats file in append only mode, so when a version is pushed
deleted and re-pushed we have some history in the stats file.

### CODE REVIEW

**Comment by FelixGV** [comment]
Good idea @arunthirupathi (:

I wonder, since the stats file format fluctuates a fair bit, should we version it?

We could have another line before the header which says something like "Stats file format: v3" or something like that.

As far as I can tell, the format already changed twice, and this will be the third. In order to make our scripts more resilient to change, this could be a useful convention to introduce. Of course, we should also document what the format version to header mapping is, which I think would be good enough to simply do in the stats' file JavaDoc.

Alternatively, we could achieve the same by giving an extension to the stat files' names, i.e.: ```.../data/read-only/<store-name>/.stats/version-x.stats-v3```.

LMK what you think of embedding some format versioning info in the files' content or name.

-F

**Comment by arunthirupathi** [comment]
@FelixGV  updated the commit , now the stats file will have a suffix -v<Version_Number>

**Comment by FelixGV** [comment]
Thanks for adding the version format. I left two minor comments. Feel free to address them or not before merging in. Otherwise LGTM.

**Comment by arunthirupathi** [comment]
Fixed.

**Pull request merged**
